### ISSUE TITLE
Gallery Submission Feedback

### ISSUE THREAD

**Issue by delsonting** [mapp-digital/Smartpixel-GTM-template#1]
in your template.tpl you invoke callInWindow, can you clarify how this method is made available? instructions were behind the login and was not clear where this method came from. Thanks.

    const trackMethod = 'wtSmart.' + data.track;
    log('Calling ' + trackMethod);
    callInWindow(trackMethod, data.keepData);

**Comment by stiegi** [comment]
Hi @delsonting sorry for the late reply - our tutorial is public now.
The method comes from our tracking script (step 1 here: https://docs.webtrekk.com/display/WIGT/Basic+implementation). We provide a helper page for the creation of a customHTML tag, which can be found here: https://zdext.webtrekk.com/gtm/

Please let me know if something is still not clear.

**Comment by delsonting** [comment]
Apologies for the delay, the reply got lost in my inbox. This template (as well as https://github.com/Webtrekk/Smartpixel-GTM-product-variable) has been approved and should appear in the template gallery in the next day. Thanks!

**Comment by stiegi** [comment]
Hi @delsonting - thank you for approving the template. In the meantime Webtrekk has been bought by Mapp Digital, and the decision has been made to rebrand the whole product. We would like to republish this from another github account under the brand Mapp Intelligence. Can we just submit the 'new' repos and delete the Webtrekk repos or is there a better way for the transition? The code is the same, only the copyright in the licence and the term 'Webtrekk' is replaced with 'Mapp Intelligence'.

**Comment by delsonting** [comment]
Use the GitHub functionality to Transfer a Repo between orgs:
https://help.github.com/en/github/administering-a-repository/transferring-a-repository.
Expect up to a couple days for all the template and metadata updated in the
Gallery.

**Comment by stiegi** [comment]
@delsonting Thank you very much for your quick help. I transferred the repo and comitted the changes.

**Comment by stiegi** [comment]
@delsonting The template still refers to github.com/Webtrekk instead of github.com/mapp-digital, while everything that was changed in the template itself was already applied. Is there a way to change the github repository link, too? In the list, we would like to see "by mapp-digital" instead of "by Webtrekk".
Thanks and best regards
